OBJS = ast.cmo parser.cmo scanner.cmo compile.cmo LFLA.cmo


# Choose one
YACC = ocamlyacc
# YACC = menhir --explain

TARFILES = Makefile scanner.mll parser.mly \
	ast.ml compile.ml LFLA.ml 

LFLA : $(OBJS)
	ocamlc -o LFLA $(OBJS)

scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	$(YACC) parser.mly

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<

.PHONY : clean
clean :
	rm -f parser.ml parser.mli scanner.ml testall.log \
	*.cmo *.cmi *.out *.diff

# Generated by ocamldep *.ml *.mli
ast.cmo: 
ast.cmx: 
compile.cmo: ast.cmo 
compile.cmx: ast.cmx 
LFLA.cmo: scanner.cmo parser.cmi compile.cmo \
    ast.cmo 
LFLA.cmx: scanner.cmx parser.cmx compile.cmx \
    ast.cmx 
parser.cmo: ast.cmo parser.cmi 
parser.cmx: ast.cmx parser.cmi 
scanner.cmo: parser.cmi 
scanner.cmx: parser.cmx 
parser.cmi: ast.cmo 
